server:
  port: 8080

rabbitmq:
  queue-name: deviceMessages

spring:
  application:
    name: iot-controller
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      authentication-database: admin