server:
  port: 8080

rabbitmq:
  queue-name: deviceMessages

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

spring:
  application:
    name: iot-controller
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: mops
    password: password
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: mops
      password: password
      authentication-database: admin
      database: mops