services:

  iot-controller:
    build:
      context: iot_controller
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mongodb
      - prometheus
      - logstash

  data-simulator:
    build:
      context: data_simulator
      dockerfile: Dockerfile
    ports:
      - "1010:1010"
    depends_on:
      - iot-controller
      - prometheus
      - logstash

  rule-engine:
    build:
      context: rule_engine
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      - iot-controller
      - rabbitmq
      - mongodb
      - prometheus
      - logstash

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: mops
      RABBITMQ_DEFAULT_PASS: password

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mops
      MONGO_INITDB_ROOT_PASSWORD: password

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: mops
      GF_SECURITY_ADMIN_PASSWORD: password
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  kibana:
      image: docker.elastic.co/kibana/kibana:7.10.1
      container_name: kibana
      environment:
        ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

volumes:
  esdata:
    driver: local