global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'data-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['data-simulator:1010']
  - job_name: 'iot-controller'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iot-controller:8080' ]
  - job_name: 'rule-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'rule-engine:6060' ]
