server:
  port: 1010

spring:
  application:
    name: data-simulator

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  file:
    name: iot-controller.log

data-simulation:
  initial-delay-millis: 60000
  device-count: 100
  frequency: 2
  indication-bound: 40

connections:
  connection-specs:
    iot-controller:
      port: 8080
      path: "/devices/%d/messages"
      host: "http://iot-controller"
