server:
  port: 9090

spring:
  application:
    name: data-simulator

data-simulation:
  device-count: 10
  frequency: 100
  indication-bound: 40

connections:
  connection-specs:
    iot-controller:
      port: 8080
      path: "/devices/%d/messages"
      host: iot-controller
