server:
  port: 1010

spring:
  application:
    name: data-simulator

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true

data-simulation:
  initial-delay-millis: 10000
  device-count: 10
  frequency: 10
  indication-bound: 40

connections:
  connection-specs:
    iot-controller:
      port: 8080
      path: "/devices/%d/messages"
      host: "http://iot-controller"
